"""
OCR Error Codes for debugging
"""


class OCRErrorCode:
    # Authentication errors (AUTH_xxx)
    AUTH_MISSING_KEY = "AUTH_MISSING_KEY"
    AUTH_INVALID_KEY = "AUTH_INVALID_KEY"
    
    # Rate limiting (RATE_xxx)
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
    
    # File errors (FILE_xxx)
    FILE_TYPE_NOT_ALLOWED = "FILE_TYPE_NOT_ALLOWED"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    FILE_EMPTY = "FILE_EMPTY"
    FILE_CORRUPTED = "FILE_CORRUPTED"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    
    # OCR processing errors (OCR_xxx)
    OCR_ENGINE_ERROR = "OCR_ENGINE_ERROR"
    OCR_NO_TEXT_FOUND = "OCR_NO_TEXT_FOUND"
    OCR_LANGUAGE_NOT_SUPPORTED = "OCR_LANGUAGE_NOT_SUPPORTED"
    OCR_TIMEOUT = "OCR_TIMEOUT"
    
    # PDF errors (PDF_xxx)
    PDF_CONVERSION_ERROR = "PDF_CONVERSION_ERROR"
    PDF_PASSWORD_PROTECTED = "PDF_PASSWORD_PROTECTED"
    PDF_TOO_MANY_PAGES = "PDF_TOO_MANY_PAGES"
    
    # MinIO errors (MINIO_xxx)
    MINIO_CONNECTION_ERROR = "MINIO_CONNECTION_ERROR"
    MINIO_OBJECT_NOT_FOUND = "MINIO_OBJECT_NOT_FOUND"
    MINIO_BUCKET_NOT_FOUND = "MINIO_BUCKET_NOT_FOUND"
    
    # General errors
    INTERNAL_ERROR = "INTERNAL_ERROR"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"
